apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}        # Service port (80)
      targetPort: {{ .Values.service.targetPort }}  # Container's target port
  selector:
    app: {{ .Release.Name }}
