replicaCount: 1

image:
  repository: 992382671809.dkr.ecr.us-east-1.amazonaws.com/my-app
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 5000 

ingress:
  enabled: false

# resources: {}
